name: 'ReviewPal Auto-Reviewers'
description: 'Automatically request PR reviewers based on git history of changed files'
author: 'Han Kim'

branding:
  icon: 'users'
  color: 'purple'

inputs:
  github_token:
    description: 'GitHub token for API access and requesting reviewers (defaults to GITHUB_TOKEN)'
    required: false
    default: ${{ github.token }}
  max_reviewers:
    description: 'Maximum number of reviewers to request'
    required: false
    default: '3'
  history_depth:
    description: 'Number of recent commits per file to consider'
    required: false
    default: '20'
  ignore_users:
    description: 'Comma-separated list of GitHub usernames to never request (in addition to PR author and bots)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Auto-assign reviewers from git history
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        PR_AUTHOR: ${{ github.event.pull_request.user.login }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        REPO: ${{ github.repository }}
        MAX_REVIEWERS: ${{ inputs.max_reviewers }}
        HISTORY_DEPTH: ${{ inputs.history_depth }}
        IGNORE_USERS: ${{ inputs.ignore_users }}
      run: |
        # Get files changed in this PR
        changed_files=$(gh pr diff "$PR_NUMBER" --name-only)

        if [ -z "$changed_files" ]; then
          echo "No changed files found, skipping."
          exit 0
        fi

        file_count=$(echo "$changed_files" | wc -l | tr -d ' ')
        echo "Found $file_count changed files"

        # Collect unique commit SHAs across all changed files
        all_shas=""
        while IFS= read -r file; do
          [ -z "$file" ] && continue
          shas=$(git log --format='%H' -"$HISTORY_DEPTH" -- "$file" 2>/dev/null)
          all_shas="$all_shas"$'\n'"$shas"
        done <<< "$changed_files"

        # Deduplicate SHAs to minimize API calls
        unique_shas=$(echo "$all_shas" | grep -v '^$' | sort -u)
        sha_count=$(echo "$unique_shas" | wc -l | tr -d ' ')
        echo "Querying $sha_count unique commits for author info..."

        # Resolve GitHub logins from commit SHAs
        all_authors=""
        for sha in $unique_shas; do
          login=$(gh api "repos/$REPO/commits/$sha" \
            --jq '.author.login // empty' 2>/dev/null)
          if [ -n "$login" ]; then
            all_authors="$all_authors"$'\n'"$login"
          fi
        done

        if [ -z "$all_authors" ]; then
          echo "Could not resolve any GitHub usernames, skipping."
          exit 0
        fi

        # Build grep exclusion pattern: PR author + bots + custom ignore list
        exclude_pattern="^${PR_AUTHOR}$"
        if [ -n "$IGNORE_USERS" ]; then
          IFS=',' read -ra IGNORE_LIST <<< "$IGNORE_USERS"
          for user in "${IGNORE_LIST[@]}"; do
            trimmed=$(echo "$user" | xargs)
            [ -n "$trimmed" ] && exclude_pattern="$exclude_pattern|^${trimmed}$"
          done
        fi

        # Count occurrences, exclude PR author/bots/ignored, take top N
        reviewers=$(echo "$all_authors" \
          | grep -v '^$' \
          | sort \
          | uniq -c \
          | sort -rn \
          | awk '{print $2}' \
          | grep -Ev "$exclude_pattern" \
          | grep -v '\[bot\]$' \
          | head -"$MAX_REVIEWERS")

        if [ -z "$reviewers" ]; then
          echo "No eligible reviewers found after filtering."
          exit 0
        fi

        echo "Requesting reviews from:"
        echo "$reviewers"

        # Request reviews
        reviewer_args=""
        for r in $reviewers; do
          reviewer_args="$reviewer_args --add-reviewer $r"
        done

        # shellcheck disable=SC2086
        gh pr edit "$PR_NUMBER" $reviewer_args || echo "Warning: could not add some reviewers (they may not have repo access)"
