name: 'ReviewPal'
description: 'AI-powered code review for any language using Claude'
author: 'Han Kim'

branding:
  icon: 'eye'
  color: 'purple'

inputs:
  anthropic_api_key:
    description: 'Anthropic API key for Claude analysis (REQUIRED)'
    required: true
  github_token:
    description: 'GitHub token for posting comments (defaults to GITHUB_TOKEN)'
    required: false
    default: ${{ github.token }}
  model:
    description: 'Claude model to use (if API key provided)'
    required: false
    default: 'claude-sonnet-4-20250514'
  max_hunks:
    description: 'Maximum number of hunks to analyze'
    required: false
    default: '20'
  comment_on_pr:
    description: 'Post analysis as PR comment'
    required: false
    default: 'true'
  format:
    description: 'Output format: friendly, json'
    required: false
    default: 'friendly'

outputs:
  total_files:
    description: 'Number of files analyzed'
  total_hunks:
    description: 'Number of hunks reviewed'
  ai_likelihood:
    description: 'Overall AI code likelihood (low/medium/high)'
  patterns_found:
    description: 'Number of patterns detected'
  high_complexity_hunks:
    description: 'Number of high-complexity hunks'
  analysis_markdown:
    description: 'Full analysis in markdown format'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      shell: bash
      run: |
        cd ${{ github.action_path }}
        npm ci --production
    
    - name: Build
      shell: bash
      run: |
        cd ${{ github.action_path }}
        npm run build
    
    - name: Get PR diff
      shell: bash
      id: diff
      run: |
        git fetch origin ${{ github.base_ref }} --depth=1
        git diff origin/${{ github.base_ref }}...HEAD > /tmp/pr.diff
        echo "diff_file=/tmp/pr.diff" >> $GITHUB_OUTPUT
        echo "lines=$(wc -l < /tmp/pr.diff)" >> $GITHUB_OUTPUT
    
    - name: Skip if no diff
      if: steps.diff.outputs.lines == '0'
      shell: bash
      run: |
        echo "No changes detected, skipping analysis"
        echo "total_files=0" >> $GITHUB_OUTPUT
        echo "total_hunks=0" >> $GITHUB_OUTPUT
        exit 0
    
    - name: Run analysis
      shell: bash
      id: analyze
      env:
        ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      run: |
        cd ${{ github.action_path }}
        
        # Run analysis (quiet mode to hide spinner)
        node dist/index.js ${{ steps.diff.outputs.diff_file }} \
          --format ${{ inputs.format }} \
          --quiet \
          --max-hunks ${{ inputs.max_hunks }} \
          --model ${{ inputs.model }} > /tmp/analysis.md 2>&1 || true
        
        # Export for outputs
        echo "analysis_markdown<<EOF" >> $GITHUB_OUTPUT
        cat /tmp/analysis.md >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
        # Also run JSON for structured data
        node dist/index.js ${{ steps.diff.outputs.diff_file }} \
          --format json \
          --quiet \
          --max-hunks ${{ inputs.max_hunks }} \
          --model ${{ inputs.model }} > /tmp/analysis.json 2>&1 || echo '{"files":[],"totalHunks":0,"aiCodeLikelihood":"low"}' > /tmp/analysis.json
        
        # Extract key metrics safely
        echo "total_files=$(jq '.files | length // 0' /tmp/analysis.json)" >> $GITHUB_OUTPUT
        echo "total_hunks=$(jq '.totalHunks // 0' /tmp/analysis.json)" >> $GITHUB_OUTPUT
        echo "ai_likelihood=$(jq -r '.aiCodeLikelihood // "low"' /tmp/analysis.json)" >> $GITHUB_OUTPUT
    
    - name: Post inline comments and summary
      if: inputs.comment_on_pr == 'true' && github.event_name == 'pull_request' && steps.analyze.outputs.total_hunks != '0'
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const fs = require('fs');
          const analysisJson = JSON.parse(fs.readFileSync('/tmp/analysis.json', 'utf8'));
          
          const EMOJI_MAP = {
            security: 'ðŸ”’',
            crash: 'ðŸ’¥',
            'data-loss': 'ðŸ—‘ï¸',
            performance: 'ðŸŒ'
          };
          
          // Collect all critical issues
          const allIssues = [];
          for (const file of analysisJson.files || []) {
            for (const hunk of file.hunks || []) {
              if (hunk.aiReview && hunk.aiReview.critical) {
                for (const issue of hunk.aiReview.critical) {
                  allIssues.push({
                    file: file.filename,
                    line: issue.line,
                    type: issue.type,
                    issue: issue.issue,
                    diffHash: hunk.hunk.fileDiffHash,
                    friendlySuggestion: issue.friendlySuggestion || issue.issue
                  });
                }
              }
            }
          }
          
          if (allIssues.length === 0) {
            console.log('No critical issues found');
            return;
          }
          
          // Post inline comments on each line and capture comment IDs
          const headSha = context.payload.pull_request.head.sha;
          const commentLinks = [];
          
          for (const item of allIssues) {
            try {
              const comment = await github.rest.pulls.createReviewComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                body: `${EMOJI_MAP[item.type] || 'âš ï¸'} **${item.type.toUpperCase()}**: ${item.friendlySuggestion}`,
                commit_id: headSha,
                path: item.file,
                line: item.line,
                side: 'RIGHT'
              });
              
              // Save comment link for summary
              commentLinks.push({
                type: item.type,
                url: comment.data.html_url,
                file: item.file,
                line: item.line
              });
            } catch (e) {
              console.log(`Failed to comment on ${item.file}:${item.line}:`, e.message);
            }
          }
          
          if (commentLinks.length === 0) {
            console.log('No comments posted');
            return;
          }
          
          // Build summary with numbered links to comments
          const issuesByType = {};
          let counter = 1;
          
          for (const item of commentLinks) {
            if (!issuesByType[item.type]) issuesByType[item.type] = [];
            issuesByType[item.type].push({
              num: counter++,
              url: item.url,
              file: item.file,
              line: item.line
            });
          }
          
          let summary = '**ReviewPal found critical issues:**\n\n';
          for (const [type, items] of Object.entries(issuesByType)) {
            const emoji = EMOJI_MAP[type] || 'âš ï¸';
            const links = items.map(i => `[${i.num}](${i.url})`).join(' ');
            summary += `${emoji} **${items.length} ${type.toUpperCase()}**: ${links}\n`;
          }
          
          summary += '\n*Click the numbers to jump to inline comments.*';
          
          // Post or update summary comment
          const marker = '<!-- reviewpal -->';
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number
          });
          
          const botComment = comments.find(c => c.body && c.body.includes(marker));
          const body = `${marker}\n\n${summary}`;
          
          if (botComment) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body
            });
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body
            });
          }
    
    - name: Check complexity threshold
      if: inputs.fail_on_high_complexity == 'true'
      shell: bash
      run: |
        COMPLEXITY=$(jq '[.files[].hunks[].complexity.score // 0] | max // 0' /tmp/analysis.json)
        if (( $(echo "$COMPLEXITY > 7" | bc -l) )); then
          echo "::error::High complexity detected (score: $COMPLEXITY)"
          exit 1
        fi
