# ReviewPal - GitHub Action Workflow
# Drop this file into .github/workflows/ to enable AI-powered code reviews
# with interactive comment replies!
#
# Features:
# - Automatic PR review on open/sync
# - Reply to user questions on ReviewPal comments
#
# Required: Add ANTHROPIC_API_KEY secret to your repository

name: ReviewPal

on:
  pull_request:
    types: [opened, synchronize, reopened]

  # Enable replies to ReviewPal comments
  pull_request_review_comment:
    types: [created]

  issue_comment:
    types: [created]

# Cancel in-progress runs on the same PR
concurrency:
  group: reviewpal-${{ github.event.pull_request.number || github.event.issue.number }}
  cancel-in-progress: true

jobs:
  # Job 1: Review PRs on open/sync
  review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ReviewPal Review
        uses: metalbear-co/reviewpal@v2
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          max_hunks: '20'
          comment_on_pr: 'true'

  # Job 2: Reply to comments on ReviewPal's review comments
  reply:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'pull_request_review_comment' ||
       github.event_name == 'issue_comment') &&
      github.event.comment.user.login != 'github-actions[bot]'

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ReviewPal Reply
        uses: metalbear-co/reviewpal/reply@v2
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
