name: 'ReviewPal Reply'
description: 'Respond to questions on ReviewPal comments and save lessons from false positives'
author: 'MetalBear'

branding:
  icon: 'message-circle'
  color: 'purple'

inputs:
  anthropic_api_key:
    description: 'Anthropic API key for Claude analysis (REQUIRED)'
    required: true
  github_token:
    description: 'GitHub token for posting comments and committing lessons (defaults to GITHUB_TOKEN)'
    required: false
    default: ${{ github.token }}
  model:
    description: 'Claude model to use'
    required: false
    default: 'claude-sonnet-4-20250514'

runs:
  using: 'composite'
  steps:
    - name: Check if this is a reply to ReviewPal
      id: check
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const comment = context.payload.comment;

          // Skip if this is our own comment
          if (comment.user.login === 'github-actions[bot]') {
            console.log('Skipping - this is our own comment');
            return;
          }

          // Check if this is a review comment (inline comment on diff)
          if (context.eventName === 'pull_request_review_comment' && context.payload.action === 'created') {
            const prNumber = context.payload.pull_request.number;
            const filePath = comment.path;
            const line = comment.line || comment.original_line;

            // Check if this is a reply to an existing comment
            if (comment.in_reply_to_id) {
              try {
                const { data: parentComment } = await github.rest.pulls.getReviewComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: comment.in_reply_to_id
                });

                const replyBody = comment.body || '';
                if (parentComment.user.login === 'github-actions[bot]' && replyBody.match(/@review-?pal\b/i)) {
                  console.log('Reply to ReviewPal comment with @review-pal mention');
                  core.setOutput('is_reviewpal_reply', 'true');
                  core.setOutput('parent_comment_body', parentComment.body);
                  core.setOutput('parent_comment_path', filePath);
                  core.setOutput('parent_comment_line', line);
                  core.setOutput('user_question', comment.body);
                  core.setOutput('comment_id', comment.id);
                  core.setOutput('pull_number', prNumber);
                  return;
                }
              } catch (e) {
                console.log('Error fetching parent comment:', e.message);
              }
            } else {
              const body = comment.body || '';
              if (body.match(/@review-?pal\b/i)) {
                console.log('User mentioned @review-pal in new comment thread');
                core.setOutput('is_reviewpal_reply', 'true');
                core.setOutput('parent_comment_body', '(User started a new discussion on this code)');
                core.setOutput('parent_comment_path', filePath);
                core.setOutput('parent_comment_line', line);
                core.setOutput('user_question', comment.body);
                core.setOutput('comment_id', comment.id);
                core.setOutput('pull_number', prNumber);
                return;
              } else {
                console.log('New comment thread but no @review-pal mention, skipping');
                core.setOutput('is_reviewpal_reply', 'false');
                return;
              }
            }
          }

          // Check if this is a reply to a PR comment (issue comment)
          if (context.eventName === 'issue_comment') {
            const body = comment.body || '';

            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });

            const reviewpalComment = comments.find(c =>
              c.user.login === 'github-actions[bot]' &&
              c.body && c.body.includes('<!-- reviewpal -->')
            );

            if (reviewpalComment) {
              if (body.match(/@review-?pal\b/i)) {
                console.log('User is asking ReviewPal a question!');
                core.setOutput('is_reviewpal_reply', 'true');
                core.setOutput('parent_comment_body', reviewpalComment.body);
                core.setOutput('user_question', comment.body);
                core.setOutput('comment_id', comment.id);
                core.setOutput('pull_number', context.issue.number);
                return;
              }
            }
          }

          console.log('Not a ReviewPal reply, skipping');
          core.setOutput('is_reviewpal_reply', 'false');

    - name: Setup Node.js
      if: steps.check.outputs.is_reviewpal_reply == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Get code context
      if: steps.check.outputs.is_reviewpal_reply == 'true'
      id: context
      shell: bash
      run: |
        if [ -n "${{ steps.check.outputs.parent_comment_path }}" ]; then
          FILE_PATH="${{ steps.check.outputs.parent_comment_path }}"
          if [ -f "$FILE_PATH" ]; then
            LINE=${{ steps.check.outputs.parent_comment_line }}
            START=$((LINE - 10))
            [ $START -lt 1 ] && START=1
            END=$((LINE + 10))
            CODE=$(sed -n "${START},${END}p" "$FILE_PATH" 2>/dev/null || echo "")
            echo "code<<EOF" >> $GITHUB_OUTPUT
            echo "$CODE" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "code=" >> $GITHUB_OUTPUT
          fi
        else
          echo "code=" >> $GITHUB_OUTPUT
        fi

    - name: Generate reply and detect lessons
      if: steps.check.outputs.is_reviewpal_reply == 'true'
      id: claude
      shell: bash
      env:
        ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}
        MODEL: ${{ inputs.model }}
        PARENT_COMMENT: ${{ steps.check.outputs.parent_comment_body }}
        USER_QUESTION: ${{ steps.check.outputs.user_question }}
        CODE_CONTEXT: ${{ steps.context.outputs.code }}
        COMMENT_PATH: ${{ steps.check.outputs.parent_comment_path }}
      run: |
        # Build prompt that also detects false positive feedback
        if [[ "$PARENT_COMMENT" == *"User started a new discussion"* ]]; then
          PROMPT="You are a helpful code reviewer. Someone left a comment on code in a PR.

        Code:
        \`\`\`
        ${CODE_CONTEXT}
        \`\`\`

        Their comment: ${USER_QUESTION}

        Respond in JSON with two fields:
        {
          \"reply\": \"Your conversational response (1-3 sentences, casual, like a friendly colleague)\",
          \"is_false_positive\": false,
          \"lesson\": null
        }"
        else
          PROMPT="You are a helpful code reviewer. Someone replied to your review comment.

        Your original comment: ${PARENT_COMMENT}

        Their reply: ${USER_QUESTION}

        File: ${COMMENT_PATH}

        Determine if the user is telling you that your finding was WRONG (a false positive).
        Signs of false positive feedback: \"wrong\", \"not an issue\", \"false positive\", \"this is fine\",
        \"disagree\", \"that's not a bug\", \"intentional\", \"by design\", \"won't fix\", \"no\", \"nah\".

        Respond in JSON:
        {
          \"reply\": \"Your conversational response (1-3 sentences, casual, acknowledge if they're right)\",
          \"is_false_positive\": true or false,
          \"lesson\": \"If is_false_positive is true: a concise lesson to remember (e.g., 'formatCurrency handles NaN by returning $0, this is intentional'). Otherwise null.\"
        }"
        fi

        RESPONSE=$(curl -s https://api.anthropic.com/v1/messages \
          -H "Content-Type: application/json" \
          -H "x-api-key: ${ANTHROPIC_API_KEY}" \
          -H "anthropic-version: 2023-06-01" \
          -d "$(jq -n \
            --arg model "${MODEL:-claude-sonnet-4-20250514}" \
            --arg prompt "$PROMPT" \
            '{model: $model, max_tokens: 800, messages: [{role: "user", content: $prompt}]}')")

        # Extract the response text
        REPLY_RAW=$(echo "$RESPONSE" | jq -r '.content[0].text // "{}"')

        # Try to parse as JSON
        REPLY=$(echo "$REPLY_RAW" | jq -r '.reply // "Got it, thanks for the feedback."' 2>/dev/null || echo "Got it, thanks for the feedback.")
        IS_FP=$(echo "$REPLY_RAW" | jq -r '.is_false_positive // false' 2>/dev/null || echo "false")
        LESSON=$(echo "$REPLY_RAW" | jq -r '.lesson // empty' 2>/dev/null || echo "")

        echo "reply<<EOF" >> $GITHUB_OUTPUT
        echo "$REPLY" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

        echo "is_false_positive=$IS_FP" >> $GITHUB_OUTPUT

        echo "lesson<<EOF" >> $GITHUB_OUTPUT
        echo "$LESSON" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Post reply
      if: steps.check.outputs.is_reviewpal_reply == 'true'
      uses: actions/github-script@v7
      env:
        REPLY_TEXT: ${{ steps.claude.outputs.reply }}
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const reply = process.env.REPLY_TEXT || 'Got it, thanks for the feedback.';
          const pullNumber = ${{ steps.check.outputs.pull_number }};
          const commentId = ${{ steps.check.outputs.comment_id }};

          try {
            await github.rest.pulls.createReplyForReviewComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pullNumber,
              comment_id: commentId,
              body: reply
            });
            console.log('Posted reply to review comment');
          } catch (e) {
            console.log('Could not reply to review comment, trying issue comment:', e.message);
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pullNumber,
              body: reply
            });
            console.log('Posted reply as issue comment');
          }

    - name: Save lesson to .reviewpal-lessons.md
      if: steps.check.outputs.is_reviewpal_reply == 'true' && steps.claude.outputs.is_false_positive == 'true'
      uses: actions/github-script@v7
      env:
        LESSON: ${{ steps.claude.outputs.lesson }}
        COMMENT_PATH: ${{ steps.check.outputs.parent_comment_path }}
        PR_NUMBER: ${{ steps.check.outputs.pull_number }}
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const lesson = process.env.LESSON;
          const filePath = process.env.COMMENT_PATH || 'unknown';
          const prNumber = process.env.PR_NUMBER;

          if (!lesson || lesson === 'null' || lesson.trim() === '') {
            console.log('No lesson to save');
            return;
          }

          const lessonsFile = '.reviewpal-lessons.md';
          const defaultBranch = context.payload.repository.default_branch || 'main';
          const newEntry = `- **${filePath}**: ${lesson} _(PR #${prNumber})_\n`;

          // Try to get existing file
          let existingContent = '';
          let existingSha = null;
          try {
            const { data } = await github.rest.repos.getContent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: lessonsFile,
              ref: defaultBranch
            });
            existingContent = Buffer.from(data.content, 'base64').toString('utf-8');
            existingSha = data.sha;
          } catch (e) {
            // File doesn't exist yet, create it
            existingContent = `# ReviewPal Lessons\n\nFalse positives and learned exceptions. ReviewPal reads this file to avoid repeating mistakes.\n\n`;
          }

          // Check for duplicate lessons (don't add the same lesson twice)
          if (existingContent.includes(lesson)) {
            console.log('Lesson already exists, skipping');
            return;
          }

          const updatedContent = existingContent.trimEnd() + '\n' + newEntry;

          // Commit to default branch via GitHub API
          const commitParams = {
            owner: context.repo.owner,
            repo: context.repo.repo,
            path: lessonsFile,
            message: `reviewpal: save lesson from PR #${prNumber}`,
            content: Buffer.from(updatedContent).toString('base64'),
            branch: defaultBranch
          };

          if (existingSha) {
            commitParams.sha = existingSha;
          }

          try {
            await github.rest.repos.createOrUpdateFileContents(commitParams);
            console.log(`Saved lesson to ${lessonsFile} on ${defaultBranch}: ${lesson}`);
          } catch (e) {
            console.log(`Failed to save lesson: ${e.message}`);
          }
