name: 'ReviewPal Reply'
description: 'Respond to questions on ReviewPal comments'
author: 'MetalBear'

branding:
  icon: 'message-circle'
  color: 'purple'

inputs:
  anthropic_api_key:
    description: 'Anthropic API key for Claude analysis (REQUIRED)'
    required: true
  github_token:
    description: 'GitHub token for posting comments (defaults to GITHUB_TOKEN)'
    required: false
    default: ${{ github.token }}
  model:
    description: 'Claude model to use'
    required: false
    default: 'claude-sonnet-4-20250514'

runs:
  using: 'composite'
  steps:
    - name: Check if this is a reply to ReviewPal
      id: check
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const comment = context.payload.comment;

          // Skip if this is our own comment
          if (comment.user.login === 'github-actions[bot]') {
            console.log('Skipping - this is our own comment');
            return;
          }

          // Check if this is a review comment (inline comment on diff)
          if (context.eventName === 'pull_request_review_comment' && context.payload.action === 'created') {
            const prNumber = context.payload.pull_request.number;
            const filePath = comment.path;
            const line = comment.line || comment.original_line;

            // Check if this is a reply to an existing comment
            if (comment.in_reply_to_id) {
              // Get the parent comment
              try {
                const { data: parentComment } = await github.rest.pulls.getReviewComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: comment.in_reply_to_id
                });

                // Check if parent is from ReviewPal
                if (parentComment.user.login === 'github-actions[bot]') {
                  console.log('This is a reply to a ReviewPal comment!');
                  core.setOutput('is_reviewpal_reply', 'true');
                  core.setOutput('parent_comment_body', parentComment.body);
                  core.setOutput('parent_comment_path', filePath);
                  core.setOutput('parent_comment_line', line);
                  core.setOutput('user_question', comment.body);
                  core.setOutput('comment_id', comment.id);
                  core.setOutput('pull_number', prNumber);
                  return;
                }
              } catch (e) {
                console.log('Error fetching parent comment:', e.message);
              }
            } else {
              // This is a NEW comment thread on the diff
              // Only respond if the user explicitly tagged @review-pal or @reviewpal
              const body = comment.body || '';
              if (body.match(/@review-?pal\b/i)) {
                console.log('User mentioned @review-pal in new comment thread - responding!');
                core.setOutput('is_reviewpal_reply', 'true');
                core.setOutput('parent_comment_body', '(User started a new discussion on this code)');
                core.setOutput('parent_comment_path', filePath);
                core.setOutput('parent_comment_line', line);
                core.setOutput('user_question', comment.body);
                core.setOutput('comment_id', comment.id);
                core.setOutput('pull_number', prNumber);
                return;
              } else {
                console.log('New comment thread but no @review-pal mention, skipping');
                core.setOutput('is_reviewpal_reply', 'false');
                return;
              }
            }
          }

          // Check if this is a reply to a PR comment (issue comment)
          if (context.eventName === 'issue_comment') {
            const body = comment.body || '';

            // Check if the comment mentions reviewpal or is replying to the summary
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });

            // Find ReviewPal's summary comment
            const reviewpalComment = comments.find(c =>
              c.user.login === 'github-actions[bot]' &&
              c.body && c.body.includes('<!-- reviewpal -->')
            );

            if (reviewpalComment) {
              // Check if user's comment mentions @review-pal or @reviewpal
              if (body.match(/@review-?pal\b/i)) {
                console.log('User is asking ReviewPal a question!');
                core.setOutput('is_reviewpal_reply', 'true');
                core.setOutput('parent_comment_body', reviewpalComment.body);
                core.setOutput('user_question', comment.body);
                core.setOutput('comment_id', comment.id);
                core.setOutput('pull_number', context.issue.number);
                return;
              }
            }
          }

          console.log('Not a ReviewPal reply, skipping');
          core.setOutput('is_reviewpal_reply', 'false');

    - name: Setup Node.js
      if: steps.check.outputs.is_reviewpal_reply == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      if: steps.check.outputs.is_reviewpal_reply == 'true'
      shell: bash
      run: |
        cd ${{ github.action_path }}
        npm ci --production

    - name: Build
      if: steps.check.outputs.is_reviewpal_reply == 'true'
      shell: bash
      run: |
        cd ${{ github.action_path }}
        npm run build

    - name: Get code context
      if: steps.check.outputs.is_reviewpal_reply == 'true'
      id: context
      shell: bash
      run: |
        # Try to get file context if we have path info
        if [ -n "${{ steps.check.outputs.parent_comment_path }}" ]; then
          FILE_PATH="${{ steps.check.outputs.parent_comment_path }}"
          if [ -f "$FILE_PATH" ]; then
            # Get surrounding lines
            LINE=${{ steps.check.outputs.parent_comment_line }}
            START=$((LINE - 10))
            [ $START -lt 1 ] && START=1
            END=$((LINE + 10))
            CODE=$(sed -n "${START},${END}p" "$FILE_PATH" 2>/dev/null || echo "")
            echo "code<<EOF" >> $GITHUB_OUTPUT
            echo "$CODE" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "code=" >> $GITHUB_OUTPUT
          fi
        else
          echo "code=" >> $GITHUB_OUTPUT
        fi

    - name: Generate reply with Claude
      if: steps.check.outputs.is_reviewpal_reply == 'true'
      id: claude
      shell: bash
      env:
        ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}
        MODEL: ${{ inputs.model }}
        PARENT_COMMENT: ${{ steps.check.outputs.parent_comment_body }}
        USER_QUESTION: ${{ steps.check.outputs.user_question }}
        CODE_CONTEXT: ${{ steps.context.outputs.code }}
      run: |
        # Build the prompt based on whether this is a reply or new thread
        if [[ "$PARENT_COMMENT" == *"User started a new discussion"* ]]; then
          PROMPT="You are a helpful code reviewer. Someone left a comment on code in a PR.

        Code:
        \`\`\`
        ${CODE_CONTEXT}
        \`\`\`

        Their comment: ${USER_QUESTION}

        Reply naturally like a friendly colleague would. Be brief - 1-3 sentences max. No bullet points or headers. Just a direct, casual response. If you don't have anything useful to add, just say something short and supportive."
        else
          PROMPT="You are a helpful code reviewer. Someone replied to your review comment.

        Your original comment: ${PARENT_COMMENT}

        Their reply: ${USER_QUESTION}

        Reply naturally like a friendly colleague would. Be brief - 1-3 sentences max. No bullet points, headers, or code blocks unless absolutely necessary. If they disagree with you and make a good point, just acknowledge it simply. Keep it conversational."
        fi

        # Call Claude API
        RESPONSE=$(curl -s https://api.anthropic.com/v1/messages \
          -H "Content-Type: application/json" \
          -H "x-api-key: ${ANTHROPIC_API_KEY}" \
          -H "anthropic-version: 2023-06-01" \
          -d "$(jq -n \
            --arg model "${MODEL:-claude-sonnet-4-20250514}" \
            --arg prompt "$PROMPT" \
            '{model: $model, max_tokens: 800, messages: [{role: "user", content: $prompt}]}')")

        # Extract the reply text
        REPLY=$(echo "$RESPONSE" | jq -r '.content[0].text // "I apologize, but I was unable to generate a response."')

        # Save to output (handle multiline)
        echo "reply<<EOF" >> $GITHUB_OUTPUT
        echo "$REPLY" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Post reply
      if: steps.check.outputs.is_reviewpal_reply == 'true'
      uses: actions/github-script@v7
      env:
        REPLY_TEXT: ${{ steps.claude.outputs.reply }}
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const reply = process.env.REPLY_TEXT || 'I apologize, but I was unable to generate a response.';
          const pullNumber = ${{ steps.check.outputs.pull_number }};
          const commentId = ${{ steps.check.outputs.comment_id }};

          // Try to reply to review comment first
          try {
            await github.rest.pulls.createReplyForReviewComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pullNumber,
              comment_id: commentId,
              body: reply
            });
            console.log('Posted reply to review comment');
          } catch (e) {
            console.log('Could not reply to review comment, trying issue comment:', e.message);
            // Fall back to issue comment
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pullNumber,
              body: reply
            });
            console.log('Posted reply as issue comment');
          }
